"""AI Village adapter.

Maps the dataset's tables (column names from its SCHEMA.md) into evidence:

  agents               -> Entity(agent), group = model family
  chat_rooms           -> Entity(resource, family "chat")
  chat_messages        -> chat.message (agent) / chat.human (user); content is an untrusted artifact
  computer_use_sessions-> session.start; session_goal is the agent's stated intention (artifact);
                          has_been_asked_to_stop -> environment.operator_stop
  summaries            -> summary.generated by a third-party summarizer (weak evidence)
  village_goals        -> goal.start
  agent_goals          -> goal.assign
  events (activity timeline, optional; chat and session rows it repeats are skipped):
    CONSOLIDATE        -> memory.consolidate (a checkpoint about every 40 actions; the next goal is the agent's own,
                          untrusted, statement of what it will do)
    PAUSE              -> agent.pause (idle, with seconds)
    SEARCH_HISTORY     -> tool.search_history (the query is not kept)
    ENTER_ROOM         -> room.enter
    OUTREACH_APPROVAL_REQUEST / _RESPONSE -> outreach.request (the drafted message and the agent's rationale are
                          untrusted artifacts; the recipient is kept as domain + hash only), then control.outreach_approved
                          or environment.outreach_denied by the human reviewer (the reviewer's comment is an artifact)
    every agent action's raw model output -> its reasoning (thinking) as an untrusted artifact on the event
                          (attributes.reasoning); for AGENT_TALK it is attached to the matching chat.message
    REQUEST_GOOGLE_SIGN_IN / RESTARTING_AFTER_GOOGLE_SIGN_IN / REQUEST_HUMAN_HELPER -> help.* (handoffs to a person)
  every agent action's cost and tokens ride along as attributes

The same mapping runs on synthetic rows written in the real schema (village_sim.py).
"""
from __future__ import annotations

import gzip
import json
import re
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Iterator

from swarmscope.core.models import Entity, EvidenceEvent
from swarmscope.ingest.adapter import Batch, make_artifact, parse_ts
from swarmscope.ingest.packs import ROOT, SourcePack

_DOMAIN = re.compile(r"\b((?:[a-z0-9-]+\.)+(?:com|org|net|io|ai|dev|app|co|edu|gov|me|xyz))\b", re.I)


def reasoning_of(output: Any) -> tuple[str, list[str]]:
    """The thinking text and the tool names in one raw model output, whatever the provider's shape (Anthropic content
    blocks, OpenAI chat or responses, Gemini candidates)."""
    think: list[str] = []
    tools: list[str] = []

    def block(b: Any) -> None:
        if not isinstance(b, dict):
            return
        t = b.get("type")
        if t == "thinking" and b.get("thinking"):
            think.append(str(b["thinking"]))
        elif t == "reasoning":
            for s in (b.get("summary") or []) + (b.get("content") or []):
                if isinstance(s, dict) and s.get("text"):
                    think.append(str(s["text"]))
        elif t in ("tool_use", "function_call") and b.get("name"):
            tools.append(str(b["name"]))
        if b.get("thought") and b.get("text"):                   # Gemini parts marked as thoughts
            think.append(str(b["text"]))
        elif b.get("functionCall"):
            tools.append(str(b["functionCall"].get("name")))

    if isinstance(output, list):
        for b in output:
            block(b)
    elif isinstance(output, dict):
        for b in output.get("content") or [] if isinstance(output.get("content"), list) else []:
            block(b)
        for k in ("reasoning", "reasoning_content"):
            if isinstance(output.get(k), str) and output[k]:
                think.append(output[k])
        for tc in output.get("tool_calls") or []:
            if isinstance(tc, dict):
                tools.append(str((tc.get("function") or {}).get("name") or tc.get("name")))
        for c in output.get("candidates") or []:
            for b in ((c or {}).get("content") or {}).get("parts") or []:
                block(b)
    return "\n\n".join(think).strip(), [t for t in tools if t and t != "None"]


def model_family(model: str | None) -> str:
    m = (model or "unknown").lower()
    if m.startswith("claude-code"):
        return "claude-code"
    for fam in ("claude", "gpt", "gemini", "grok", "deepseek", "kimi", "qwen", "llama", "mistral", "o1", "o3", "o4"):
        if fam in m:
            return "openai" if fam in ("gpt", "o1", "o3", "o4") else fam
    return re.split(r"[-/:._]", m)[0] or "unknown"


class AIVillageAdapter:
    id = "ai_village"

    def __init__(self, pack: SourcePack):
        self.pack = pack
        self.cfg = pack.source
        self.families = {k: re.compile(v, re.I) for k, v in (self.cfg.get("resource_families") or {}).items()}

    def capabilities(self):
        return self.pack.capabilities

    # ------------------------------------------------------------------ io
    def _rows(self, root: Path, table: str) -> Iterator[dict[str, Any]]:
        f = root / self.cfg["schema"][table]["file"]
        if not f.exists():
            return iter(())
        return (json.loads(line) for line in gzip.open(f, "rt", encoding="utf-8") if line.strip())

    def load(self, path: str | None, slice_override: dict[str, Any] | None = None) -> Batch:
        root = Path(path or self.cfg.get("default_path", "data/ai_village"))
        if not root.is_absolute():
            root = ROOT / root
        if path == "synthetic" or not (root / self.cfg["schema"]["agents"]["file"]).exists():
            from swarmscope.sources.village_sim import write_synthetic
            root = write_synthetic(ROOT / "data" / "ai_village_synthetic")
            self.pack.capabilities.synthetic = True
        return self._map(root, {**(self.cfg.get("slice") or {}), **(slice_override or {})})

    # ------------------------------------------------------------------ slice
    def _slice_bounds(self, root: Path, sl: dict[str, Any]) -> tuple[datetime, datetime, str | None]:
        goal_text = None
        if sl.get("goal"):
            for g in self._rows(root, "village_goals"):
                if str(g["id"]).startswith(str(sl["goal"])):
                    start = parse_ts(g.get("start_time"))
                    end = parse_ts(g.get("end_time")) or (start + timedelta(days=7))
                    goal_text = g.get("goal")
                    return start, end, goal_text
        start = parse_ts(sl.get("start")) or datetime(2000, 1, 1)
        end = parse_ts(sl.get("end")) or (start + timedelta(days=7) if sl.get("start") else datetime(2100, 1, 1))
        return start, end, goal_text

    def _family(self, text: str) -> tuple[str, str]:
        """(family, resource id) for a session goal."""
        fam = next((name for name, pat in self.families.items() if pat.search(text or "")), "computer")
        dom = _DOMAIN.search(text or "")
        if dom:
            d = dom.group(1).lower()
            return fam, f"dom:{d}"
        return fam, f"res:{fam}"

    # ------------------------------------------------------------------ mapping
    _OUTREACH = re.compile(r"mail|reddit|hacker|ycombinator|lesswrong|forum|youtube|twitter|github|form|post|x\b", re.I)

    def _timeline(self, root: Path, in_slice, agents: dict[str, Entity], rooms: dict[str, Entity],
                  resources: dict[str, Entity], active: set[str], events: list[EvidenceEvent], b: Batch,
                  operator: Entity) -> None:
        src = self.id

        def place(rid: str, label: str, fam: str) -> str:
            if rid not in resources:
                resources[rid] = Entity(id=rid, type="resource", source=src, label=label, group=fam,
                                        attributes={"family": fam})
            return rid

        chat_ev = {e.id: e for e in events if e.action == "chat.message"}

        def text_art(key: str, text: str, ts, actor, prov: str) -> str | None:
            if not text or not str(text).strip():
                return None
            art, body = make_artifact(f"art:{key}", str(text), ts, actor, prov)
            b.artifacts.append((art, body))
            return art.id

        for r in self._rows(root, "events"):
            d = r.get("data") or {}
            t = d.get("actionType")
            ts = parse_ts(r.get("created_at"))
            aid = d.get("agentId") or (d.get("speakerId") if t == "AGENT_TALK" else None)
            if not in_slice(ts) or aid not in agents or t in ("USER_TALK", None):
                continue
            think, tools = reasoning_of(d.get("output"))
            why = text_art(f"{r['id']}:reasoning", think, ts, aid, f"events.{t}.output") if think else None
            if t == "AGENT_TALK":                       # the message itself is already in chat; add its reasoning
                ce = chat_ev.get(f"ev:{d.get('messageId')}")
                if ce is not None and why:
                    ce.attributes["reasoning"] = why
                continue
            cost = {k: d[k] for k in ("cost", "inputTokens", "outputTokens") if isinstance(d.get(k), (int, float))}
            if why:
                cost["reasoning"] = why                  # rides along with the cost attributes on every action
            if tools:
                cost["tools"] = tools[:6]
            loc = f"events#{r.get('event_index', r['id'])}"
            room = d.get("roomId")
            ev = None
            if t == "CONSOLIDATE":
                goal = d.get("nextSessionGoal") or d.get("nextShortDisplayedSessionGoal") or ""
                fam, rid = self._family(goal)
                place(rid, rid.split(":", 1)[1] if rid.startswith("dom:") else fam, fam)
                art, text = make_artifact(f"art:{r['id']}", goal, ts, aid, "events.CONSOLIDATE")
                b.artifacts.append((art, text))
                ev = EvidenceEvent(id=f"ev:{r['id']}", ts=ts, source=src, actor=aid, action="memory.consolidate",
                                   object=rid, artifact=art.id,
                                   attributes={"family": fam, "session": d.get("computerUseSessionId"),
                                               "short_goal": (d.get("nextShortDisplayedSessionGoal") or "")[:90], **cost},
                                   locator=loc)
            elif t == "PAUSE":
                ev = EvidenceEvent(id=f"ev:{r['id']}", ts=ts, source=src, actor=aid, action="agent.pause", object=None,
                                   attributes={"family": "idle", "seconds": d.get("seconds"), **cost}, locator=loc)
            elif t == "SEARCH_HISTORY":
                rid = place("res:village-history", "village history", "research")
                q = text_art(f"{r['id']}:query", d.get("query") or "", ts, aid, "events.SEARCH_HISTORY.query")
                ans = text_art(f"{r['id']}:answer", d.get("answerToQuery") or "", ts, None, "events.SEARCH_HISTORY.answer")
                ev = EvidenceEvent(id=f"ev:{r['id']}", ts=ts, source=src, actor=aid, action="tool.search_history",
                                   object=rid, artifact=q, attributes={"family": "research", "answer": ans,
                                                                       "days": [d.get("startDay"), d.get("endDay")], **cost},
                                   locator=loc)
            elif t == "ENTER_ROOM" and room in rooms:
                ev = EvidenceEvent(id=f"ev:{r['id']}", ts=ts, source=src, actor=aid, action="room.enter", object=room,
                                   attributes={"family": "chat", "room": rooms[room].label, **cost}, locator=loc)
            elif t in ("OUTREACH_APPROVAL_REQUEST", "OUTREACH_APPROVAL_RESPONSE"):
                medium = str(d.get("medium") or "outreach").lower()
                kind = "email" if "mail" in medium else "social post" if self._OUTREACH.search(medium) else "outreach"
                rid = place(f"res:outreach:{kind}", f"outreach by {kind}", "outreach")
                rc = d.get("recipient") if isinstance(d.get("recipient"), dict) else {}
                who = {"recipient_domain": rc.get("domain") or None, "recipient": rc.get("hash") or None,
                       "request": d.get("outreachApprovalRequestId")}
                if t == "OUTREACH_APPROVAL_REQUEST":
                    msg = text_art(f"{r['id']}:message", d.get("messageContent") or "", ts, aid, "events.OUTREACH.message")
                    rat = text_art(f"{r['id']}:rationale", d.get("rationale") or "", ts, aid, "events.OUTREACH.rationale")
                    ev = EvidenceEvent(id=f"ev:{r['id']}", ts=ts, source=src, actor=aid, action="outreach.request",
                                       object=rid, artifact=msg, attributes={"family": "outreach", "medium": kind,
                                                                             "rationale": rat, **who, **cost}, locator=loc)
                else:
                    ok = d.get("approval") is True
                    note = text_art(f"{r['id']}:comment", d.get("adminComment") or "", ts, operator.id,
                                    "events.OUTREACH.admin_comment")
                    ev = EvidenceEvent(id=f"ev:{r['id']}", ts=ts, source=src, actor=operator.id,
                                       action="control.outreach_approved" if ok else "environment.outreach_denied",
                                       object=rid, artifact=note, attributes={"family": "outreach", "medium": kind,
                                                                              "target_agent": aid, **who},
                                       locator=loc)
            elif t in ("REQUEST_GOOGLE_SIGN_IN", "RESTARTING_AFTER_GOOGLE_SIGN_IN", "REQUEST_HUMAN_HELPER"):
                rid = place("res:human-help", "help from a person", "ops")
                if t == "REQUEST_HUMAN_HELPER":
                    cost["request"] = text_art(f"{r['id']}:ask", d.get("sessionGoal") or "", ts, aid, "events.HUMAN_HELPER")
                act = {"REQUEST_GOOGLE_SIGN_IN": "help.sign_in_request", "RESTARTING_AFTER_GOOGLE_SIGN_IN": "help.sign_in_done",
                       "REQUEST_HUMAN_HELPER": "help.human_request"}[t]
                ev = EvidenceEvent(id=f"ev:{r['id']}", ts=ts, source=src, actor=aid, action=act, object=rid,
                                   attributes={"family": "ops", **cost}, locator=loc)
            if ev is not None:
                events.append(ev)
                active.add(aid)

    def _map(self, root: Path, sl: dict[str, Any]) -> Batch:
        start, end, goal_text = self._slice_bounds(root, sl)
        b = Batch()
        src = self.id
        in_slice = lambda ts: ts is not None and start <= ts < end  # noqa: E731

        agents: dict[str, Entity] = {}
        for a in self._rows(root, "agents"):
            e = Entity(id=a["id"], type="agent", source=src, label=a.get("name") or a["id"][:8],
                       group=model_family(a.get("model_string")), identity_confidence="strong",
                       attributes={"model": a.get("model_string"), "participating": a.get("is_participating")})
            agents[e.id] = e
        rooms = {r["id"]: Entity(id=r["id"], type="resource", source=src, label=f"#{r.get('name') or r['id'][:6]}",
                                 group="chat", attributes={"family": "chat"}) for r in self._rows(root, "rooms")}
        resources: dict[str, Entity] = {}
        humans: dict[str, Entity] = {}
        active: set[str] = set()
        events: list[EvidenceEvent] = []
        summarizer = Entity(id="summarizer", type="summarizer", source=src, label="Village summarizer",
                            identity_confidence="weak", group="third-party")
        operator = Entity(id="operator", type="human", source=src, label="Village operator", group="humans")

        # goals
        for g in self._rows(root, "village_goals"):
            ts = parse_ts(g.get("start_time"))
            if in_slice(ts) or (goal_text and g.get("goal") == goal_text):
                gid = f"goal:{g['id']}"
                resources[gid] = Entity(id=gid, type="goal", source=src, label="Village goal", group="goals",
                                        attributes={"family": "goal"})
                art, text = make_artifact(f"art:{gid}", g.get("goal") or "", ts, None, "village_goals")
                b.artifacts.append((art, text))
                events.append(EvidenceEvent(id=f"ev:{gid}", ts=max(ts, start), source=src, actor=None,
                                            action="goal.start", object=gid, artifact=art.id,
                                            attributes={"family": "goal"}, locator=f"village_goals#{g['id']}"))
        for g in self._rows(root, "agent_goals"):
            ts = parse_ts(g.get("start_time")) or start
            if in_slice(ts) and g.get("agent_id") in agents:
                gid = f"agoal:{g['id']}"
                resources[gid] = Entity(id=gid, type="goal", source=src, label=g.get("short_name") or "Agent goal",
                                        group="goals", attributes={"family": "goal"})
                art, text = make_artifact(f"art:{gid}", f"{g.get('name') or ''}\n{g.get('description') or ''}",
                                          ts, g["agent_id"], "agent_goals")
                b.artifacts.append((art, text))
                events.append(EvidenceEvent(id=f"ev:{gid}", ts=ts, source=src, actor=g["agent_id"],
                                            action="goal.assign", object=gid, artifact=art.id,
                                            attributes={"family": "goal"}, locator=f"agent_goals#{g['id']}"))
                active.add(g["agent_id"])

        # chat
        for c in self._rows(root, "chat"):
            ts = parse_ts(c.get("created_at"))
            if not in_slice(ts):
                continue
            room = c.get("room_id")
            if c.get("speaker_type") == "agent" and c.get("agent_speaker_id") in agents:
                actor, action = c["agent_speaker_id"], "chat.message"
                active.add(actor)
            else:
                uid = c.get("user_speaker_id") or "anon"
                actor = f"human:{uid[:8]}"
                humans.setdefault(actor, Entity(id=actor, type="human", source=src, label=f"viewer {uid[:4]}",
                                                group="humans"))
                action = "chat.human"
            art, text = make_artifact(f"art:{c['id']}", c.get("content") or "", ts, actor, "chat_messages")
            b.artifacts.append((art, text))
            events.append(EvidenceEvent(id=f"ev:{c['id']}", ts=ts, source=src, actor=actor, action=action,
                                        object=room, artifact=art.id,
                                        attributes={"family": "chat", "room": rooms[room].label if room in rooms else room,
                                                    "chars": len(text), "labels": art.labels},
                                        locator=f"chat_messages#{c['id']}"))

        # computer-use sessions
        for s in self._rows(root, "sessions"):
            ts = parse_ts(s.get("created_at"))
            if not in_slice(ts) or s.get("agent_id") not in agents:
                continue
            actor = s["agent_id"]
            active.add(actor)
            goal = s.get("session_goal") or s.get("short_displayed_session_goal") or ""
            fam, rid = self._family(goal)
            if rid not in resources:
                resources[rid] = Entity(id=rid, type="resource", source=src,
                                        label=rid.split(":", 1)[1] if rid.startswith("dom:") else fam,
                                        group=fam, attributes={"family": fam})
            art, text = make_artifact(f"art:{s['id']}", goal, ts, actor, "computer_use_sessions")
            b.artifacts.append((art, text))
            short = (s.get("short_displayed_session_goal") or "")[:90]
            events.append(EvidenceEvent(id=f"ev:{s['id']}", ts=ts, source=src, actor=actor, action="session.start",
                                        object=rid, artifact=art.id,
                                        attributes={"family": fam, "session": s["id"], "short_goal": short},
                                        locator=f"computer_use_sessions#{s['id']}"))
            if s.get("has_been_asked_to_stop"):
                events.append(EvidenceEvent(id=f"ev:stop:{s['id']}", ts=ts + timedelta(seconds=1), source=src,
                                            actor="operator", action="environment.operator_stop", object=rid,
                                            attributes={"family": fam, "session": s["id"], "target_agent": actor},
                                            locator=f"computer_use_sessions#{s['id']}.has_been_asked_to_stop"))

        # the activity timeline: what agents did between messages and sessions
        self._timeline(root, in_slice, agents, rooms, resources, active, events, b, operator)

        # third-party summaries (weak)
        for s in self._rows(root, "summaries"):
            ts = parse_ts(s.get("created_at"))
            if not in_slice(ts):
                continue
            art, text = make_artifact(f"art:{s['id']}", s.get("content") or "", ts, "summarizer", "summaries")
            b.artifacts.append((art, text))
            events.append(EvidenceEvent(id=f"ev:{s['id']}", ts=ts, source=src, actor="summarizer",
                                        action="summary.generated", object=None, artifact=art.id,
                                        attributes={"family": "summary", "type": s.get("type"),
                                                    "target": s.get("summary_target"), "by": s.get("generated_by")},
                                        locator=f"summaries#{s['id']}"))

        events.sort(key=lambda e: (e.ts, e.id))
        b.entities = [a for a in agents.values() if a.id in active] + list(rooms.values()) + \
            list(resources.values()) + list(humans.values()) + [summarizer, operator]
        b.events = events
        b.meta = {"slice_start": start, "slice_end": end, "goal_text": goal_text, "root": str(root)}
        return b
